name: Metasploit Framework Acceptance

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on:
  workflow_dispatch:
    inputs:
      metasploitFrameworkCommit:
        description: 'metasploit-framework branch would like to test'
        required: true
        default: 'fix/mettle-macos-15-sigabrt'
  push:
    branches-ignore:
      - gh-pages
      - metakitty
  pull_request:
    branches:
      - '*'

jobs:
  build:
    uses: SaiSakthidar/metasploit-framework/.github/workflows/shared_meterpreter_acceptance.yml@fix/mettle-macos-15-sigabrt
    with:
      metasploit_framework_repository: SaiSakthidar/metasploit-framework
      metasploit_framework_commit: ${{ github.event.inputs.metasploitFrameworkCommit }}
      build_mettle: true
      mettle_repository: ${{ github.repository }}
      mettle_commit: ${{ github.sha }}
